version: '3.3'

services:
  # python:
  #   image: lehungio/python:latest
  #   volumes:
  #       - ./:/code
  
  python_build:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - ".:/code"
    command: python3 manage.py runserver 0.0.0.0:8083
    ports:
      - "8083:8083"

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      # - python
      - python_build